#!/bin/bash

# ExamRoot Authentication Setup Guide

echo "🔐 ExamRoot Authentication Setup Complete!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "QUICK START GUIDE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 BACKEND SETUP (Server)"
echo "────────────────────────────"
echo "1. Configure .env file with:"
echo "   - MONGO_URI: MongoDB connection string"
echo "   - JWT_SECRET: Secret key for JWT tokens"
echo "   - EMAIL_SERVICE: gmail (or other)"
echo "   - EMAIL_USER: Your email address"
echo "   - EMAIL_PASSWORD: Your app password (not regular password)"
echo ""
echo "2. For Gmail:"
echo "   - Enable 2-factor authentication"
echo "   - Generate App Password at: https://myaccount.google.com/apppasswords"
echo "   - Use App Password in EMAIL_PASSWORD"
echo ""
echo "3. Start backend:"
echo "   cd server"
echo "   npm install"
echo "   npm start"
echo ""
echo ""
echo "📱 MOBILE SETUP (Expo App)"
echo "──────────────────────────"
echo "1. Install dependencies:"
echo "   cd mobile"
echo "   npm install"
echo ""
echo "2. Start Expo:"
echo "   npm start"
echo ""
echo "3. Update IP in baseUrl.js if needed:"
echo "   src/utils/baseUrl.js - PHYSICAL_DEVICE_IP"
echo ""
echo ""
echo "🔑 AUTHENTICATION FLOW"
echo "──────────────────────"
echo "1. User enters email on LOGIN screen"
echo "2. Backend sends OTP via email"
echo "3. User enters OTP on VERIFICATION screen"
echo "4. NEW USERS: Enter username"
echo "5. EXISTING USERS: Auto-login"
echo "6. Token saved in AsyncStorage"
echo "7. App redirects to HOME screen"
echo ""
echo ""
echo "📝 TESTING THE FLOW"
echo "───────────────────"
echo "Email: test@example.com"
echo "OTP: Check backend logs OR email inbox"
echo "Username: testuser (for new signup)"
echo ""
echo ""
echo "🛠️ TROUBLESHOOTING"
echo "──────────────────"
echo "❌ OTP not received:"
echo "   → Check email credentials in .env"
echo "   → Enable Less Secure Apps for Gmail"
echo "   → Check console logs for errors"
echo ""
echo "❌ Backend connection fails:"
echo "   → Check MONGO_URI in .env"
echo "   → Verify MongoDB is running"
echo ""
echo "❌ Auth state not persisting:"
echo "   → Clear AsyncStorage: expo r -c"
echo "   → Restart app"
echo ""
echo ""
echo "📚 DOCUMENTATION"
echo "────────────────"
echo "Full docs available in: AUTHENTICATION_SETUP.md"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ Setup complete! Your app is ready for authentication."
echo "════════════════════════════════════════════════════════════"
