/**
 * Fast2SMS Quick SMS utility — No DLT required
 * API: POST https://www.fast2sms.com/dev/bulkV2  (route: "q")
 * Docs: https://docs.fast2sms.com/reference/quick-sms-post
 *
 * OTP is generated by us, stored in our DB, and verified by us.
 * Fast2SMS only delivers the SMS — it does NOT manage OTP state.
 */

const F2S_BULK_URL = "https://www.fast2sms.com/dev/bulkV2";
const API_KEY = () => process.env.FAST2SMS_API_KEY;

/**
 * Send OTP via Fast2SMS Quick SMS (no DLT needed)
 * @param {string} mobile - 10-digit Indian mobile number
 * @param {string} otp    - 6-digit OTP generated by our server
 */
export const sendSMSOTP = async (mobile, otp) => {
  const cleanMobile = mobile.replace(/\D/g, "").slice(-10);

  const message = `${otp} is your ExamRoot OTP. Valid for 10 minutes. Do not share with anyone.`;

  // ── Dev bypass: print OTP to console instead of sending SMS ─────────────
  if (process.env.NODE_ENV !== "production") {
    console.log(`\n📱 [DEV] SMS OTP for ${cleanMobile}: ${otp}\n`);
    return { return: true, dev: true };
  }

  const res = await fetch(F2S_BULK_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "authorization": API_KEY(),
    },
    body: JSON.stringify({
      route:   "q",
      message,
      numbers: cleanMobile,   // POST endpoint uses "numbers", not "qnumbers"
    }),
  });

  const data = await res.json();

  // Fast2SMS returns { return: true/false, message: [...], request_id, ... }
  console.log("Fast2SMS response:", JSON.stringify(data));

  if (!res.ok || data?.return === false) {
    console.error("❌ Fast2SMS send failed:", data);
    const errMsg = Array.isArray(data?.message)
      ? data.message.join(", ")
      : (data?.message || "Failed to send SMS OTP");
    throw new Error(errMsg);
  }

  console.log("✅ SMS OTP sent to:", cleanMobile);
  return data;
};
